// List of types for Google Places api
export const TYPES_NAME_OBJECTS = [
  { type: "accounting" },
  { type: "airport" },
  { type: "amusement_park" },
  { type: "aquarium" },
  { type: "art_gallery" },
  { type: "atm" },
  { type: "bakery" },
  { type: "bank" },
  { type: "bar" },
  { type: "beauty_salon" },
  { type: "bicycle_store" },
  { type: "book_store" },
  { type: "bowling_alley" },
  { type: "bus_station" },
  { type: "cafe" },
  { type: "campground" },
  { type: "car_dealer" },
  { type: "car_rental" },
  { type: "car_repair" },
  { type: "car_wash" },
  { type: "casino" },
  { type: "cemetery" },
  { type: "church" },
  { type: "city_hall" },
  { type: "clothing_store" },
  { type: "convenience_store" },
  { type: "courthouse" },
  { type: "dentist" },
  { type: "department_store" },
  { type: "doctor" },
  { type: "drugstore" },
  { type: "electrician" },
  { type: "electronics_store" },
  { type: "embassy" },
  { type: "fire_station" },
  { type: "florist" },
  { type: "funeral_home" },
  { type: "furniture_store" },
  { type: "gas_station" },
  { type: "gym" },
  { type: "hair_care" },
  { type: "hardware_store" },
  { type: "hindu_temple" },
  { type: "home_goods_store" },
  { type: "hospital" },
  { type: "insurance_agency" },
  { type: "jewelry_store" },
  { type: "laundry" },
  { type: "lawyer" },
  { type: "library" },
  { type: "light_rail_station" },
  { type: "liquor_store" },
  { type: "local_government_office" },
  { type: "locksmith" },
  { type: "lodging" },
  { type: "meal_delivery" },
  { type: "meal_takeaway" },
  { type: "mosque" },
  { type: "movie_rental" },
  { type: "movie_theater" },
  { type: "moving_company" },
  { type: "museum" },
  { type: "night_club" },
  { type: "painter" },
  { type: "park" },
  { type: "parking" },
  { type: "pet_store" },
  { type: "pharmacy" },
  { type: "physiotherapist" },
  { type: "plumber" },
  { type: "police" },
  { type: "post_office" },
  { type: "primary_school" },
  { type: "real_estate_agency" },
  { type: "restaurant" },
  { type: "roofing_contractor" },
  { type: "rv_park" },
  { type: "school" },
  { type: "secondary_school" },
  { type: "shoe_store" },
  { type: "shopping_mall" },
  { type: "spa" },
  { type: "stadium" },
  { type: "storage" },
  { type: "store" },
  { type: "subway_station" },
  { type: "supermarket" },
  { type: "synagogue" },
  { type: "taxi_stand" },
  { type: "tourist_attraction" },
  { type: "train_station" },
  { type: "transit_station" },
  { type: "travel_agency" },
  { type: "university" },
  { type: "veterinary_care" },
  { type: "zoo" }
];

// Used to help convert measurement types.
// API uses meters but this will help with UI.
// First two nums are measure -> meters and meters -> measure.
// Final num is Earths radius in respected measurement.
export const MEASUREMENT_KEYS = {
  "miles": [1609.34, 0.00062137, 3958.756],
  "kilometers": [1000, 0.001, 6371] 
};

// Used for caching data.
export const STORAGE_KEY = "8b1a9953c4611296a827abf8c47804d7";